services:
  api:
    build: .
    ports:
    - "8080:8080"
    environment:
      PG_USER: user
      PG_DATABASE: crud_database
      PG_PASSWORD: 123456789
      PG_PORT: 5432
      API_KEY: 42815e653c4afa616d1347f0476abb63ffcd88dfc14a9e7328f844ff83270597
    depends_on:
      - db

  db:
    image: postgres:18
    restart: always
    ports:
    - "5432:5432"
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: 123456789
      POSTGRES_DB: crud_database
    volumes:
      - db_data:/var/lib/postgresql
      - ./db.config/init.sql:/docker-entrypoint-initdb.d/init.sql

volumes:
  db_data: